Added side ruler object
deJcob/STM32_PBLV5 pull request #1
Opened 2021-05-30 13:47 UTC by JacekJurek

Change logic of expander index iterating and added sideRulerObject

2021-05-31 08:19 UTC, deJcob requested changes
You have to read sensors from the side ruler in TIM6!

2021-06-06 13:29 UTC, JacekJurek commented
Fixed pulling data from sideRulerSensors

2021-06-06 13:51 UTC, deJcob approved these changes

2021-06-06 16:41 UTC, JacekJurek commented on PBLV5/Core/Inc/globalDefines.h
> +#define ID_SIDE_RULER 0x13
Keep in mind changing its id before merging (conflict with currentMeasurement branch)

2021-06-28 09:39 UTC, closed without merging